language: python

python:
- 2.7

script:
- pip install file://$(pwd)

deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist bdist_wheel"
  password:
    secure: YtlMrnT8XqB3sAm9ludEI3DbW5Warh25+6C2gg3+nDhW7/tTcyh4bfxtaTnzCq28qHOM6hSQpZ5xett/jLW+EFRCBr9O8R78Vd3jMsSEn7VMfRy1+XVwyEwg8yXRltT1810pdXRQfKIarG/63lf+Jikm72ecnRsn7dHPRMAYoJ8=
  on:
    tags: true
    repo: pyblish/pyblish-maya
